Init with multiple branches
codex-team/deployserver pull request #10
Opened 2019-06-19 19:04 UTC by dyadyaJora

Добавлено:
* возможность настраивать автоматический деплой на несколько веток
* регулярные выражения для определения названия веток
* обратный вызов `deployscript` с передачей в cli параметра c названием ветки (эту функциональность регулирует флаг `params['branches']['is_branch_name_to_cli'])`

* поправил проверку веток для bitbucket (не мог отследить название веток вида `deploy/test`)

2019-06-19 21:49 UTC, n0str requested changes

2019-06-19 21:49 UTC, n0str commented on deployserver/__init__.py
> +            val['regexp'] = re.compile(val.get('regexp'))
Нужно обработать Exception в случае неверного регулярного выражения

2019-06-20 11:34 UTC, kabachook requested changes

2019-06-20 11:34 UTC, kabachook commented on deployserver/__init__.py
> +        'branches': settings.get('branches', []),
Обновить доки вверху

2019-06-20 11:34 UTC, kabachook commented on deployserver/__init__.py
> +                subprocess.Popen([cmd], shell=True)
Лучше сделать так:
```
cmd = [script, current_branch] if is_branch_name_to_cli else [script]
subprocess.Popen(cmd, shell=True)
```

1. Убирает нужду в экранировании
2. Не нужно возится с пробелами

2019-06-20 11:34 UTC, kabachook commented on deployserver/__init__.py
> +            _check_params_branches(branch)
Два раза вызовется деплой

2019-06-20 11:35 UTC, kabachook commented on deployserver/__init__.py
> +                subprocess.Popen([cmd], shell=True)
+ bash injection

2019-06-20 11:36 UTC, n0str commented on deployserver/__init__.py
> +                subprocess.Popen([cmd], shell=True)
Предлагаю вообще убрать этот хак. 
Не нужно нам имя бранча в скрипте.

2019-06-21 10:51 UTC, kabachook commented on deployserver/__init__.py
> +                subprocess.Popen([cmd], shell=True)
на каждый бранч свой скрипт?

2019-06-26 15:50 UTC, n0str commented on deployserver/__init__.py
> +                subprocess.Popen([cmd], shell=True)
Ага. Почему бы и нет.

2019-06-30 14:21 UTC, n0str commented on deployserver/__init__.py
> +            val['regexp'] = re.compile(val.get('regexp'))
А точнее вынести компиляцию regex на этап инициализации

2019-06-30 17:56 UTC, n0str commented on deployserver/__init__.py
> +                print('Run deploy script [' + script + '] for branch [' + current_branch + ']...')
В таких случаях следует использовать .format

2019-06-30 18:05 UTC, dyadyaJora commented on deployserver/__init__.py
> +            val['regexp'] = re.compile(val.get('regexp'))
это же вроде и есть этап инициализации
обработку ошибок добавил

2019-06-30 19:30 UTC, n0str approved these changes
Можешь бампать версию и тестировать работает ли python server.py install

2019-06-30 19:33 UTC, kabachook approved these changes

2019-07-01 17:47 UTC, merged